<?php 
    if(!isset($_GET['content'])) { $_GET['content'] = ""; }
    if ($_GET['content'] == "") { include ("../Templates/Help/start.tpl"); }
    if ($_GET['content'] == "start") { include ("../Templates/Help/start.tpl"); }
    if ($_GET['content'] == "archive") { include ("../Templates/Help/Start/archive.tpl"); }
    if ($_GET['content'] == "links") { include ("../Templates/Help/Start/links.tpl"); }
    if ($_GET['content'] == "tutorials") { include ("../Templates/Help/tutorials.tpl"); }
    if ($_GET['content'] == "gameplay") { include ("../Templates/Help/Tutorials/gameplay.tpl"); }
    if ($_GET['content'] == "tuttxt") { include ("../Templates/Help/Tutorials/Gameplay/tuttxt.tpl"); }
    if ($_GET['content'] == "tutvideo") { include ("../Templates/Help/Tutorials/Gameplay/tutvideo.tpl"); }
    if ($_GET['content'] == "misc") { include ("../Templates/Help/Tutorials/misc.tpl"); }
    if ($_GET['content'] == "tutmaps") { include ("../Templates/Help/Tutorials/Misc/tutmap.tpl"); }
    if ($_GET['content'] == "build") { include ("../Templates/Help/buildings.tpl"); }
    if ($_GET['content'] == "buildoverview") { include ("../Templates/Help/Build/buildoverview.tpl"); }
    if ($_GET['content'] == "structure") { include ("../Templates/Help/Build/structure.tpl"); }
    if ($_GET['content'] == "brewery") { include ("../Templates/Help/Build/Infrastructure/brewery.tpl"); }
    if ($_GET['content'] == "cranny") { include ("../Templates/Help/Build/Infrastructure/cranny.tpl"); }
    if ($_GET['content'] == "embassy") { include ("../Templates/Help/Build/Infrastructure/embassy.tpl"); }
    if ($_GET['content'] == "granary") { include ("../Templates/Help/Build/Infrastructure/granary.tpl"); }
    if ($_GET['content'] == "greatgranary") { include ("../Templates/Help/Build/Infrastructure/greatgranary.tpl"); }
    if ($_GET['content'] == "greatwarehouse") { include ("../Templates/Help/Build/Infrastructure/greatwarehouse.tpl"); }
    if ($_GET['content'] == "horsedrink") { include ("../Templates/Help/Build/Infrastructure/horsedrink.tpl"); }
    if ($_GET['content'] == "mainbuilding") { include ("../Templates/Help/Build/Infrastructure/mainbuilding.tpl"); }
    if ($_GET['content'] == "marketplace") { include ("../Templates/Help/Build/Infrastructure/marketplace.tpl"); }
    if ($_GET['content'] == "palace") { include ("../Templates/Help/Build/Infrastructure/palace.tpl"); }
    if ($_GET['content'] == "residence") { include ("../Templates/Help/Build/Infrastructure/residence.tpl"); }
    if ($_GET['content'] == "stonemason") { include ("../Templates/Help/Build/Infrastructure/stonemason.tpl"); }
    if ($_GET['content'] == "townhall") { include ("../Templates/Help/Build/Infrastructure/townhall.tpl"); }
    if ($_GET['content'] == "tradeoffice") { include ("../Templates/Help/Build/Infrastructure/tradeoffice.tpl"); }
    if ($_GET['content'] == "treasury") { include ("../Templates/Help/Build/Infrastructure/treasury.tpl"); }
    if ($_GET['content'] == "warehouse") { include ("../Templates/Help/Build/Infrastructure/warehouse.tpl"); }
    if ($_GET['content'] == "ww") { include ("../Templates/Help/Build/Infrastructure/ww.tpl"); }
    if ($_GET['content'] == "military") { include ("../Templates/Help/Build/military.tpl"); }
    if ($_GET['content'] == "academy") { include ("../Templates/Help/Build/Military/academy.tpl"); }
    if ($_GET['content'] == "armoury") { include ("../Templates/Help/Build/Military/armoury.tpl"); }
    if ($_GET['content'] == "barracks") { include ("../Templates/Help/Build/Military/barracks.tpl"); }
    if ($_GET['content'] == "blacksmith") { include ("../Templates/Help/Build/Military/blacksmith.tpl"); }
    if ($_GET['content'] == "citywall") { include ("../Templates/Help/Build/Military/citywall.tpl"); }
    if ($_GET['content'] == "earthwall") { include ("../Templates/Help/Build/Military/earthwall.tpl"); }
    if ($_GET['content'] == "greatbarracks") { include ("../Templates/Help/Build/Military/greatbarracks.tpl"); }
    if ($_GET['content'] == "greatstable") { include ("../Templates/Help/Build/Military/greatstable.tpl"); }
    if ($_GET['content'] == "heromansion") { include ("../Templates/Help/Build/Military/heromansion.tpl"); }
    if ($_GET['content'] == "palisade") { include ("../Templates/Help/Build/Military/palisade.tpl"); }
    if ($_GET['content'] == "rallypoint") { include ("../Templates/Help/Build/Military/rallypoint.tpl"); }
    if ($_GET['content'] == "stable") { include ("../Templates/Help/Build/Military/stable.tpl"); }
    if ($_GET['content'] == "tournamentsquare") { include ("../Templates/Help/Build/Military/tournamentsquare.tpl"); }
    if ($_GET['content'] == "trapper") { include ("../Templates/Help/Build/Military/trapper.tpl"); }
    if ($_GET['content'] == "workshop") { include ("../Templates/Help/Build/Military/workshop.tpl"); }
    if ($_GET['content'] == "resources") { include ("../Templates/Help/Build/resources.tpl"); }
    if ($_GET['content'] == "bakery") { include ("../Templates/Help/Build/Resources/bakery.tpl"); }
    if ($_GET['content'] == "brickyard") { include ("../Templates/Help/Build/Resources/brickyard.tpl"); }
    if ($_GET['content'] == "claypit") { include ("../Templates/Help/Build/Resources/claypit.tpl"); }
    if ($_GET['content'] == "cropland") { include ("../Templates/Help/Build/Resources/cropland.tpl"); }
    if ($_GET['content'] == "grainmill") { include ("../Templates/Help/Build/Resources/grainmill.tpl"); }
    if ($_GET['content'] == "ironfoundry") { include ("../Templates/Help/Build/Resources/ironfoundry.tpl"); }
    if ($_GET['content'] == "ironmine") { include ("../Templates/Help/Build/Resources/ironmine.tpl"); }
    if ($_GET['content'] == "sawmill") { include ("../Templates/Help/Build/Resources/sawmill.tpl"); }
    if ($_GET['content'] == "woodcutter") { include ("../Templates/Help/Build/Resources/woodcutter.tpl"); }
    if ($_GET['content'] == "troops") { include ("../Templates/Help/troops.tpl"); }
    if ($_GET['content'] == "gallictroops") { include ("../Templates/Help/Troops/gallictroops.tpl"); }
    if ($_GET['content'] == "heroes") { include ("../Templates/Help/Troops/heroes.tpl"); }
    if ($_GET['content'] == "makeanduse") { include ("../Templates/Help/Troops/makeanduse.tpl"); }
    if ($_GET['content'] == "natariantroops") { include ("../Templates/Help/Troops/natariantroops.tpl"); }
    if ($_GET['content'] == "naturetroops") { include ("../Templates/Help/Troops/naturetroops.tpl"); }
    if ($_GET['content'] == "romantroops") { include ("../Templates/Help/Troops/romantroops.tpl"); }
    if ($_GET['content'] == "teutonictroops") { include ("../Templates/Help/Troops/teutonictroops.tpl"); }
    if ($_GET['content'] == "game") { include ("../Templates/Help/game.tpl"); }
    if ($_GET['content'] == "alliances") { include ("../Templates/Help/Game/alliances.tpl"); }
    if ($_GET['content'] == "artefacts") { include ("../Templates/Help/Game/artefacts.tpl"); }
    if ($_GET['content'] == "beginnersprotection") { include ("../Templates/Help/Game/beginnersprotection.tpl"); }
    if ($_GET['content'] == "cancellingactions") { include ("../Templates/Help/Game/cancellingactions.tpl"); }
    if ($_GET['content'] == "capitals") { include ("../Templates/Help/Game/capitals.tpl"); }
    if ($_GET['content'] == "changelog") { include ("../Templates/Help/Game/changelog.tpl"); }
    if ($_GET['content'] == "conqueringvillages") { include ("../Templates/Help/Game/conqueringvillages.tpl"); }
    if ($_GET['content'] == "culturepoints") { include ("../Templates/Help/Game/culturepoints.tpl"); }
    if ($_GET['content'] == "faqtplus") { include ("../Templates/Help/Game/faqtplus.tpl"); }
    if ($_GET['content'] == "gamerules") { include ("../Templates/Help/Game/gamerules.tpl"); }
    if ($_GET['content'] == "gettingfarmed") { include ("../Templates/Help/Game/gettingfarmed.tpl"); }
    if ($_GET['content'] == "interactivingwithothers") { include ("../Templates/Help/Game/interactivingwithothers.tpl"); }
    if ($_GET['content'] == "map") { include ("../Templates/Help/Game/map.tpl"); }
    if ($_GET['content'] == "messagesandreports") { include ("../Templates/Help/Game/messagesandreports.tpl"); }
    if ($_GET['content'] == "miscellaneous") { include ("../Templates/Help/Game/miscellaneous.tpl"); }
    if ($_GET['content'] == "newvillages") { include ("../Templates/Help/Game/newvillages.tpl"); }
    if ($_GET['content'] == "oases") { include ("../Templates/Help/Game/oases.tpl"); }
    if ($_GET['content'] == "population") { include ("../Templates/Help/Game/population.tpl"); }
    if ($_GET['content'] == "preventingconquerings") { include ("../Templates/Help/Game/preventingconquerings.tpl"); }
    if ($_GET['content'] == "problemswithcorp") { include ("../Templates/Help/Game/problemswithcorp.tpl"); }
    if ($_GET['content'] == "statistics") { include ("../Templates/Help/Game/statistics.tpl"); }
    if ($_GET['content'] == "tplusandgold") { include ("../Templates/Help/Game/tplusandgold.tpl"); }
    if ($_GET['content'] == "tribes") { include ("../Templates/Help/Game/tribes.tpl"); }
    if ($_GET['content'] == "profile") { include ("../Templates/Help/profile.tpl"); }
    if ($_GET['content'] == "overviewprofile") { include ("../Templates/Help/Profile/overviewprofile.tpl"); }
    if ($_GET['content'] == "renamingvillages") { include ("../Templates/Help/Profile/renamingvillages.tpl"); }
    if ($_GET['content'] == "preferences") { include ("../Templates/Help/Profile/preferences.tpl"); }
    if ($_GET['content'] == "account") { include ("../Templates/Help/Profile/account.tpl"); }
    if ($_GET['content'] == "gpacks") { include ("../Templates/Help/Profile/gpacks.tpl"); }
    if ($_GET['content'] == "irc") { include ("../Templates/Help/irc.tpl"); }
    if ($_GET['content'] == "ircrules") { include ("../Templates/Help/IRC/ircrules.tpl"); }
    if ($_GET['content'] == "irctut") { include ("../Templates/Help/IRC/irctut.tpl"); }
    if ($_GET['content'] == "channels") { include ("../Templates/Help/IRC/Tutorials/channels.tpl"); }
    if ($_GET['content'] == "chatzilla") { include ("../Templates/Help/IRC/Tutorials/chatzilla.tpl"); }
    if ($_GET['content'] == "memos") { include ("../Templates/Help/IRC/Tutorials/memos.tpl"); }
    if ($_GET['content'] == "miranda") { include ("../Templates/Help/IRC/Tutorials/miranda.tpl"); }
    if ($_GET['content'] == "mirc") { include ("../Templates/Help/IRC/Tutorials/mirc.tpl"); }
    if ($_GET['content'] == "nicknames") { include ("../Templates/Help/IRC/Tutorials/nicknames.tpl"); }
    if ($_GET['content'] == "trillian") { include ("../Templates/Help/IRC/Tutorials/trillian.tpl"); }
    if ($_GET['content'] == "services") { include ("../Templates/Help/IRC/services.tpl"); }
    if ($_GET['content'] == "dict") { include ("../Templates/Help/dictionary.tpl"); }
    if ($_GET['content'] == "buildings") { include ("../Templates/Help/Dictionary/buildings.tpl"); }
    if ($_GET['content'] == "forumchat") { include ("../Templates/Help/Dictionary/forumchat.tpl"); }
    if ($_GET['content'] == "dgame") { include ("../Templates/Help/Dictionary/dgame.tpl"); }
    if ($_GET['content'] == "smilies") { include ("../Templates/Help/Dictionary/smilies.tpl"); }
    if ($_GET['content'] == "travianxteam") { include ("../Templates/Help/Dictionary/travianxteam.tpl"); }
    if ($_GET['content'] == "dtroops") { include ("../Templates/Help/Dictionary/dtroops.tpl"); }
    if ($_GET['content'] == "sitemap") { include ("../Templates/Help/sitemap.tpl"); }
?>